import Head from "next/head";
// import getConfig from 'next/config';
import axios from "axios";
import { useEffect, useState } from "react";
import Row from "../components/Row";
// const {serverRuntimeConfig, publicRuntimeConfig} = getConfig()
export default function Home() {
  const [content, setContent] = useState([]);

  const fetchData = async () => {
    const { data } = await axios.get(
      `https://api.themoviedb.org/3/trending/all/day?api_key=${process.env.apiKey}`
    );
    // console.log(data)
    setContent(data.results);
  };

  useEffect(() => {
    fetchData();
  }, []);
  console.log(content);
  return (
    <div>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Trending</h1>
      <div className="content">
       
        {content &&
          content.map((item) => {
            return (
              
              <Row
                key={item.id}
                id={item.id}
                media_type={item.media_type}
                title={item.title || item.name}
                release_date={item.release_date || item.first_air_date}
                poster = {item.poster_path}
              />
            );
          })}
      </div>
    </div>
  );
}

// export async function getServerSideProps(context){
//   // const API_KEY = "cdf8a09bf5371e89768bbfa5343ac793";
//   let trendingMovies = await fetch(`https://api.themoviedb.org/3/movie/550?api_key=${process.env.NEXT_PUBLIC_API_KEY}`)
//   trendingMovies = await trendingMovies.json();
//   console.log(trendingMovies);
//   return{
//     props: {trendingMovies: trendingMovies},
//   }
// }
